## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [29]:
from sklearn.model_selection import train_test_split, KFold
import numpy as np

# Note: test_size=0.33 表示 1/3 當作測試, 也就是 10*1/3 = 6 筆

X_train, X_test, y_train, y_test = train_test_split(X[:40], y[:40], test_size=10, random_state=1)
X_train_G, X_test_G, y_train_G, y_test_G = train_test_split(X[40:], y[40:], test_size=10, random_state=1)

print(f'{X_train.shape}, {X_test.shape}, {y_train.shape}, {y_test.shape}')
print(f'{X_train_G.shape}, {X_test_G.shape}, {y_train_G.shape}, {y_test_G.shape}')

X_train = np.vstack([X_train, X_train_G])
X_test = np.vstack([X_test, X_test_G])
y_train = np.hstack([y_train, y_train_G])
y_test = np.hstack([y_test, y_test_G])

(30, 5), (10, 5), (30,), (10,)
(150, 5), (10, 5), (150,), (10,)


In [30]:
y_train

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [40]:
# Note: 
#    以下兩者在 array dimension 不為 1 時候是不同的, 因為 append 會自動展開為 1 維的, 
#    因為我們是 2 維 array, 所以要用 vstack
#
#    X_train = np.vstack([X_train, X_train_G])
#    np.append(X_train, X_train_G)
#
#    但是 dimension = 1 時, hstack 與 append 的效果是相同的

print(f'np.vstack([X_train, X_train_G]) = {np.vstack([X_train, X_train_G]).shape}')

print(f'np.append(X_train, X_train_G).shape = {np.append(X_train, X_train_G).shape}')

np.vstack([X_train, X_train_G]) = (330, 5)
np.append(X_train, X_train_G).shape = (1650,)


In [41]:
# 
print(f'np.append(X_train, X_train_G).shape = {np.append(X_train, X_train_G).shape}')
np.append(X_train, X_train_G)

np.append(X_train, X_train_G).shape = (1650,)


array([160, 161, 162, ..., 387, 388, 389])